name: ci-cd-qc
run-name: Build, Deploy to UAT and Test - from user @${{ github.actor }}

on: 
  workflow_dispatch:
    inputs:
      sut:
        description: 'Testsystem IP address'
        required: true

env:
  UAT_IP: ${{ inputs.sut }}
  UAT_TOMCAT: /home/ec2-user/tomcat/apache-tomcat-9.0.71/webapps
  UAT_PORT: 22

jobs:
  check_env: 
    runs-on: ubuntu-latest
    environment: UAT
    
    steps: 
     - name: print IP address
       run: echo ${{ env.UAT_IP }}
       
     - name: lookup if $UAT_IP is accessible
       uses: appleboy/ssh-action@master
       with:
         host: ${{ env.UAT_IP }}
         username: ${{ secrets.USER }}
         key: ${{ secrets.SSH_KEY }}
         port: ${{ env.UAT_PORT }}
    
  build_and_test_and_deploy:
    needs: [check_env]
    environment: UAT
    name: Build, Run Unit Tests, and Check Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Run Unit Tests with Coverage
        run: mvn clean test jacoco:report

      - name: Build with Maven
        run: mvn -DskipTests -B package --no-transfer-progress --file ./pom.xml

      - name: rename Artefakt
        run: mv ./target/*digitalbank*.war ./target/digibank.war

      - uses: actions/upload-artifact@master
        with:
          name: digibank.war
          path: ./target/digibank*
      
      - name: cleanup destination at $UAT_IP
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.UAT_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ env.UAT_PORT }}
          script: rm -rf ./deployment/*

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.UAT_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ env.UAT_PORT }}
          source: './target/digibank.war'
          target: 'deployment'

      - name: Upload Code Coverage Report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: target/site/jacoco/index.html

      - name: Check Code Coverage Threshold
        run: |
          threshold=$(awk -F'[<>]' '/
          counter value=""/{print $3}' target/site/jacoco/index.html)
          if [[ "$threshold" -lt "80" ]]; then
          echo "Code coverage is below threshold. Exiting..."
          exit 1
          fi
          
  install:
    needs: [build_and_test_and_deploy]
    environment: UAT
    name: Install Application
    runs-on: ubuntu-latest

    steps:
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.UAT_IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ env.UAT_PORT }}
          script: cp -f /home/ec2-user/deployment/target/digibank.war ${{ env.UAT_TOMCAT }}
          
  automation_tests:
    needs: install
    environment: UAT
    name: Trigger E2E Tests on UAT Environment
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow from e2e tests with Playwright
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/e2e-pipeline-workshop/digibank-playwright-tests/dispatches \
          -d  '{"event_type": "trigger-tests", "client_payload" : { "sut" : "${{ env.UAT_IP }}" } }'
